Combined AHN + BGT fuser for buildings
Amsterdam-AI-Team/Urban_PointCloud_Processing pull request #21
Opened 2021-08-10 09:36 UTC by daanbl

* Building fuser using both BGT and AHN.

* TopBottomLCC is now LayerLCC, which allows more flexibility in defining layers.

* Bugfix in clip_utils

* Update datasets for demo.

2021-08-10 10:01 UTC, chrise96 requested changes

2021-08-10 10:04 UTC, daanbl commented on src/fusion/bgt_fuser.py
> +            if self.ahn_reader is not None:
Klopt!

2021-08-10 18:47 UTC, chrise96 approved these changes

2021-08-11 07:20 UTC, closed without merging

2021-08-11 07:20 UTC, daanbl commented
Commits are not showing up, closing this PR and opening a new one.